[package]
name = "openapi-edit"
version = "0.1.1"
edition = "2024"

[dependencies]
eframe = { version = "0.31", features = ["persistence"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
rfd = "0.15"
ureq = "3"
image = { version = "0.25", default-features = false, features = ["png"] }
